import test from 'node:test';
import assert from 'node:assert/strict';
import {makeHandler} from '../api/alpaca-connection.js';
const key='unit-test-key-1234567890',secret='unit-test-secret-1234567890';
async function request({status=200,body={apiKey:key,secretKey:secret},origin='https://1d1phocheol.vercel.app',empty=false,malformed=false}={}){let called=false;const handler=makeHandler({env:{NODE_ENV:'production',ALPACA_API_KEY:'never-use-env-key'},fetchImpl:async(url,options)=>{called=true;const u=new URL(url);assert.equal(u.origin,'https://data.alpaca.markets');assert.equal(u.pathname,'/v2/stocks/bars');assert.equal(u.searchParams.get('feed'),'iex');assert.equal(u.searchParams.get('symbols'),'AAPL');assert.equal(options.headers['APCA-API-KEY-ID'],key);assert.equal(options.headers['APCA-API-SECRET-KEY'],secret);assert.equal(options.method,undefined);return {ok:status===200,status,json:async()=>malformed?{}:{bars:{AAPL:empty?[]:[{t:'2026-10-02T04:00:00Z',o:1,h:2,l:1,c:2,v:10}]},message:secret}}}});const res={headers:{},setHeader(k,v){this.headers[k]=v},end(raw){this.raw=raw;this.body=JSON.parse(raw)}};await handler({method:'POST',headers:{origin,'content-type':'application/json'},body},res);assert.equal(res.raw.includes(secret),false);assert.equal(res.raw.includes(key),false);assert.equal(res.raw.includes('never-use-env'),false);assert.equal(res.headers['Cache-Control'],'no-store');return {...res,called};}
test('Alpaca verification uses only read-only IEX bars and returns no price data',async()=>{const r=await request();assert.equal(r.statusCode,200);assert.equal(r.body.persisted,false);assert.equal(r.body.feed,'iex');assert.equal(r.body.mode,'market-data-read-only');assert.equal(r.body.bars,undefined);assert.equal(r.body.hasData,true)});
test('Alpaca credentials and same-origin request are both required',async()=>{for(const options of [{body:{}},{body:{apiKey:key}},{origin:'https://evil.example'}]){const r=await request(options);assert.ok(r.statusCode>=400);assert.equal(r.called,false)}});
test('empty response is not a fabricated data point',async()=>{const r=await request({empty:true});assert.equal(r.body.verified,true);assert.equal(r.body.hasData,false)});
test('malformed data and failed authentication never expose upstream details',async()=>{assert.equal((await request({malformed:true})).statusCode,502);for(const status of [401,403,429,500])assert.ok((await request({status})).statusCode>=400)});
