import test from 'node:test';
import assert from 'node:assert/strict';
import sodium from 'libsodium-wrappers';
import {makeHandler} from '../api/credentials.js';
await sodium.ready;
const pair=sodium.crypto_box_keypair(),admin='github_pat_fake_admin_1234567890',apiKey='fake-alpaca-key-123456',secretKey='fake-alpaca-secret-123456';
async function request({login='simhocheol',action='save',provider='alpaca',origin='https://1d1phocheol.vercel.app',authorized=true,writeStatus=201}={}){const calls=[];let plaintext;const handler=makeHandler({env:{NODE_ENV:'production'},fetchImpl:async(url,options)=>{calls.push({url,options});assert.equal(options.headers.Authorization,`Bearer ${admin}`);const path=new URL(url).pathname;const response=(status,data)=>({ok:status>=200&&status<300,status,json:async()=>data});if(path==='/user')return response(200,{login});if(path.endsWith('/public-key'))return response(200,{key_id:'public-1',key:sodium.to_base64(pair.publicKey,sodium.base64_variants.ORIGINAL)});if(options.method==='PUT'){const body=JSON.parse(options.body);assert.deepEqual(Object.keys(body).sort(),['encrypted_value','key_id']);assert.equal(options.body.includes(secretKey),false);plaintext=sodium.to_string(sodium.crypto_box_seal_open(sodium.from_base64(body.encrypted_value,sodium.base64_variants.ORIGINAL),pair.publicKey,pair.privateKey));return response(writeStatus,{message:'never-return-upstream-private-details'})}return response(path.endsWith('/ALPACA_CREDENTIALS_JSON')?200:404,{updated_at:'2026-10-04T00:00:00Z',value:secretKey})}});const res={headers:{},setHeader(k,v){this.headers[k]=v},end(raw){this.raw=raw;this.body=JSON.parse(raw)}};await handler({method:'POST',headers:{origin,'content-type':'application/json',...(authorized?{authorization:`Bearer ${admin}`}:{})},body:{action,provider,apiKey:provider==='openai'?'sk-fake-key-12345678901234567890':apiKey,secretKey}},res);assert.equal(res.raw.includes(admin),false);assert.equal(res.raw.includes(secretKey),false);assert.equal(res.raw.includes(apiKey),false);assert.equal(res.raw.includes('never-return'),false);assert.equal(res.headers['Cache-Control'],'no-store');return {...res,calls,plaintext};}
test('Alpaca pair is sealed and saved as one atomic GitHub secret',async()=>{const r=await request();assert.equal(r.statusCode,200);assert.equal(r.body.persisted,true);assert.deepEqual(JSON.parse(r.plaintext),{apiKey,secretKey});const writes=r.calls.filter(c=>c.options.method==='PUT');assert.equal(writes.length,1);assert.ok(writes[0].url.endsWith('/ALPACA_CREDENTIALS_JSON'));});
test('OpenAI key is encrypted into its existing workflow secret',async()=>{const r=await request({provider:'openai'});assert.equal(r.plaintext,'sk-fake-key-12345678901234567890');assert.ok(r.calls.at(-1).url.endsWith('/OPENAI_API_KEY'));});
test('missing auth, other owner and cross-origin requests cannot change keys',async()=>{for(const option of [{authorized:false},{login:'someone-else'},{origin:'https://untrusted.example'}]){const r=await request(option);assert.ok(r.statusCode>=400);assert.equal(r.calls.filter(c=>c.options.method==='PUT').length,0)}});
test('status exposes only configured flags and update timestamps',async()=>{const r=await request({action:'status'});assert.equal(r.statusCode,200);assert.equal(r.body.saved.alpaca.configured,true);assert.equal(r.body.saved.openai.configured,false);assert.equal(r.plaintext,undefined);assert.equal(r.body.secretKey,undefined)});
test('failed write must not claim a successful save',async()=>{const r=await request({writeStatus:403});assert.equal(r.statusCode,403);assert.notEqual(r.body.persisted,true)});
