import React,{useEffect,useState} from 'react';
import {Button} from '@heroui/react';
import {Eye,EyeOff,ShieldCheck,ExternalLink} from 'lucide-react';
import {SecretSave,useCredentialStore} from './credential-store.jsx';
export default function AlpacaSettings(){
 const [key,setKey]=useState(''),[secret,setSecret]=useState(''),[visible,setVisible]=useState(false),[pending,setPending]=useState(false),[result,setResult]=useState(null),[saved,setSaved]=useState(null);
 useEffect(()=>{const c=new AbortController();fetch('/data/market-connection.json',{signal:c.signal,cache:'no-cache'}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(setSaved).catch(()=>{});return()=>c.abort()},[]);
 const store=useCredentialStore();
 function clear(){setKey('');setSecret('');setVisible(false)}
 async function submit(e){e.preventDefault();if(pending)return;if(!store?.authenticated){setResult({ok:false,text:'먼저 GitHub 관리자 인증을 완료해 주세요.'});return}setPending(true);setResult(null);try{const r=await fetch('/api/alpaca-connection',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({apiKey:key.trim(),secretKey:secret.trim()}),cache:'no-store'});const body=await r.json();if(!r.ok||body.verified!==true){setResult({ok:false,text:body.message||'연결 확인 실패'});return}try{const saved=await store.persist('alpaca',{apiKey:key.trim(),secretKey:secret.trim()});setResult({ok:true,text:`연결 확인 성공 · ${saved.message}`})}catch{setResult({ok:false,text:'연결은 성공했지만 암호화 저장에 실패했습니다. 관리자 권한을 확인하고 키를 다시 입력해 주세요.'})}}catch{setResult({ok:false,text:'연결 테스트 서버에 접근하지 못했습니다.'})}finally{clear();setPending(false)}}
 return <section className="api-settings alpaca-settings"><div className="api-section-heading"><h2>Alpaca 시장 데이터</h2><span>선택됨 · Basic / IEX · 읽기 전용</span></div><p className="fine">미국 주식·ETF · 일봉 OHLCV · 주문·계좌 접근 미사용</p><p className="fine">서버 연결 확인: {saved?.status==='verified'?'인증·IEX 접근 확인':saved?.status==='error'?'연결 실패':saved?.status==='missing_keys'?'키 등록 대기':'미확인'}{saved?.checkedAt&&` · ${new Date(saved.checkedAt).toLocaleString('ko-KR')}`}</p>
 <form onSubmit={submit}><label htmlFor="alpaca-key">Alpaca API Key</label><div className="api-key-row"><input id="alpaca-key" type={visible?'text':'password'} value={key} onChange={e=>{setKey(e.target.value);setResult(null)}} autoComplete="off" autoCapitalize="none" spellCheck={false} maxLength={256} placeholder="API Key" disabled={pending} required/><Button isIconOnly variant="ghost" title={visible?'Alpaca 키 숨기기':'Alpaca 키 보기'} aria-label={visible?'Alpaca 키 숨기기':'Alpaca 키 보기'} onPress={()=>setVisible(!visible)}>{visible?<EyeOff size={17}/>:<Eye size={17}/>}</Button></div><label htmlFor="alpaca-secret">Alpaca Secret Key</label><div className="api-key-row"><input id="alpaca-secret" type={visible?'text':'password'} value={secret} onChange={e=>{setSecret(e.target.value);setResult(null)}} autoComplete="off" autoCapitalize="none" spellCheck={false} maxLength={256} placeholder="Secret Key" disabled={pending} required/><Button type="submit" variant="primary" isDisabled={pending||!key.trim()||!secret.trim()}><ShieldCheck size={16}/>{pending?'확인 중':'Alpaca 연결 테스트'}</Button></div></form>
 <SecretSave provider="alpaca" credentials={{apiKey:key,secretKey:secret}} onResult={setResult} onClear={clear} disabled={pending}/>
 {result&&<p role="status" className={result.ok?'positive':'negative'}>{result.text}</p>}<p className="fine">관리자 인증 후 연결 테스트가 성공하면 자동으로 암호화 저장됩니다. 암호화 저장은 두 키를 하나의 Secret으로 함께 등록합니다. 처리 후 입력값은 지우며 저장된 원문은 다시 표시하지 않습니다.</p><div className="api-registration"><h3>저장한 키 사용</h3><p>암호화 저장한 키는 다음 예약 수집 또는 수동 실행에서 사용됩니다. 저장 후 관리자 인증을 해제하거나 새로고침해도 키는 유지됩니다. 공개 가격 표시는 별도 권한 확인 후 연결합니다.</p><a href="https://app.alpaca.markets/" target="_blank" rel="noreferrer">Alpaca 가입·키 발급 <ExternalLink size={14}/></a><a href="https://github.com/simhocheol/1D1P/settings/secrets/actions" target="_blank" rel="noreferrer">저장소 등록 목록 <ExternalLink size={14}/></a></div><p className="api-license-warning">IEX 가격·거래량은 전체 시장 통합 데이터가 아닙니다. 공개 표시·재배포 권한 확인 전에는 가격 데이터를 게시하지 않습니다.</p></section>
}
