import React,{useState} from 'react';
import {Button} from '@heroui/react';
import {KeyRound,Eye,EyeOff,ExternalLink,ShieldCheck} from 'lucide-react';
import './api-settings.css';
import AlpacaSettings from './alpaca-settings.jsx';
import {SecretSave,useCredentialStore} from './credential-store.jsx';
const providers=[
 {name:'Alpaca Basic',scope:'미국 주식 · ETF',limit:'무료 · 과거 데이터 API 200회/분',detail:'무료 실시간은 IEX 범위. 전체 시장 거래량이 아니며, 과거 데이터의 최근 15분 접근 제한이 있습니다.',url:'https://docs.alpaca.markets/us/docs/about-market-data-api',signup:'https://alpaca.markets/data',fit:'개인 개발·분석용 우선 후보'},
 {name:'Twelve Data Basic',scope:'미국 주식 · ETF',limit:'무료 · 8크레딧/분 · 800크레딧/일',detail:'종목별 time_series는 1크레딧. 500종목 × 하루 2회는 1,000크레딧으로 무료 한도를 초과합니다. 기본 플랜은 internal non-display 용도입니다.',url:'https://twelvedata.com/pricing',signup:'https://twelvedata.com/register',fit:'소규모 내부 분석 후보'},
 {name:'Alpha Vantage',scope:'주식 시계열 · 지표',limit:'무료 · 25회/일',detail:'전체 500종목 수집에는 부족합니다. 실시간·15분 지연 데이터는 별도 이용 권한을 확인해야 합니다.',url:'https://www.alphavantage.co/support/',signup:'https://www.alphavantage.co/support/#api-key',fit:'소수 종목 테스트 후보'},
];
function OpenaiSettings(){
 const [key,setKey]=useState(''),[visible,setVisible]=useState(false),[pending,setPending]=useState(false),[result,setResult]=useState(null);const store=useCredentialStore();
 function clear(){setKey('');setVisible(false)}
 async function submit(e){e.preventDefault();if(pending)return;if(!store?.authenticated){setResult({ok:false,text:'먼저 GitHub 관리자 인증을 완료해 주세요.'});return}setPending(true);setResult(null);try{const response=await fetch('/api/openai-connection',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({apiKey:key.trim()}),cache:'no-store'});const data=await response.json();if(!response.ok||data.verified!==true){setResult({ok:false,text:data.message||'연결 확인에 실패했습니다.'});return}try{const saved=await store.persist('openai',{apiKey:key.trim()});setResult({ok:true,text:`연결 확인 성공 · ${saved.message}`})}catch{setResult({ok:false,text:'연결은 성공했지만 암호화 저장에 실패했습니다. 관리자 권한을 확인하고 키를 다시 입력해 주세요.'})}}catch{setResult({ok:false,text:'연결 테스트 서버에 접근하지 못했습니다.'})}finally{clear();setPending(false)}}
 return <section className="api-settings"><div className="api-section-heading"><KeyRound size={19}/><h2>OpenAI API 연결</h2><span>{store?.saved?.openai?.configured?'암호화 저장됨':'관리자 인증 후 저장 상태 확인'} · 자동 요약 미연결</span></div><form onSubmit={submit}><label htmlFor="openai-api-key">API 키 · 연결 테스트</label><div className="api-key-row"><input id="openai-api-key" type={visible?'text':'password'} value={key} onChange={e=>{setKey(e.target.value);setResult(null)}} placeholder="sk-..." autoComplete="off" autoCapitalize="none" spellCheck={false} maxLength={520} disabled={pending} required/><Button isIconOnly variant="ghost" title={visible?'키 숨기기':'키 보기'} aria-label={visible?'키 숨기기':'키 보기'} onPress={()=>setVisible(!visible)}>{visible?<EyeOff size={17}/>:<Eye size={17}/>}</Button><Button type="submit" variant="primary" isDisabled={pending||!key.trim()}><ShieldCheck size={16}/>{pending?'확인 중':'연결 테스트'}</Button></div></form>
 <SecretSave provider="openai" credentials={{apiKey:key}} onResult={setResult} onClear={clear} disabled={pending}/>
 {result&&<p role="status" className={result.ok?'positive':'negative'}>{result.text}</p>}<p className="fine">관리자 인증 후 연결 테스트가 성공하면 자동으로 암호화 저장됩니다. 암호화 저장은 OPENAI_API_KEY Secret으로 등록합니다. 처리 후 입력란은 지우며 키 원문을 다시 불러오지 않습니다. 자동 요약 생성은 별도 연결이 필요합니다.</p><a href="https://platform.openai.com/api-keys" target="_blank" rel="noreferrer">OpenAI 키 발급 <ExternalLink size={14}/></a></section>
}
export default function ApiSettings(){return <><AlpacaSettings/><OpenaiSettings/><section className="api-provider-section"><div className="api-section-heading"><h2>무료 시장 데이터 API 후보</h2><span>공식 문서 확인 · 2026.10.04</span></div><div className="api-provider-list">{providers.map(p=><article key={p.name}><small>{p.fit}</small><h3>{p.name}</h3><p>{p.scope}</p><strong>{p.limit}</strong><p>{p.detail}</p><a href={p.url} target="_blank" rel="noreferrer">공식 제공 범위 <ExternalLink size={13}/></a><a href={p.signup} target="_blank" rel="noreferrer">가입·키 발급 <ExternalLink size={13}/></a></article>)}</div><p className="api-license-warning">무료 개발용 접근과 공개 서비스 재배포 권한은 별개입니다. 제공처·거래소의 외부 표시 권한을 확인하기 전에는 이 공개 사이트에 자동 가격 표시를 연결하지 않습니다. IEX 거래량을 전체 시장 거래량으로 표시하지 않습니다.</p></section></>}
