import React,{useState} from 'react';
import {Button} from '@heroui/react';
import {ChevronLeft,ChevronRight,ArrowUpRight,CalendarDays,ExternalLink} from 'lucide-react';
import {calendarEvents,monthDays} from './calendar-data.js';
import {verifiedSessions} from './verified-sessions.js';
import OfficialFeed,{useOfficialFeed} from './official-feed.jsx';
import MonthlyDrivers from './monthly-drivers.jsx';
import './styles.css';import './dark.css';import './calendar.css';import './framework.css';
const labels={economic:'경제지표',institution:'기관 발표',earnings:'실적 발표'};
export default function CalendarPage(){const today=new Date();const [month,setMonth]=useState(new Date(Date.UTC(today.getFullYear(),today.getMonth(),1))),[day,setDay]=useState(today.getDate()),[category,setCategory]=useState('all'),[view,setView]=useState('month');const {data,error}=useOfficialFeed();
 const y=month.getUTCFullYear(),m=month.getUTCMonth(),count=monthDays(y,m),prefix=`${y}-${String(m+1).padStart(2,'0')}`,date=`${prefix}-${String(day).padStart(2,'0')}`;
 const feedEvents=(data?.events||[]).map(e=>({...e,day:Number(e.date.slice(-2)),type:'institution',source:e.agency,time:new Date(e.publishedAt).toLocaleTimeString('en-US',{timeZone:'America/New_York',hour:'2-digit',minute:'2-digit'})+' ET',note:'원문 제목·게시 시각 자동 수집. Driver 분류·영향 분석 대기.',drivers:[]}));
 const events=[...calendarEvents,...feedEvents].filter(e=>e.date.startsWith(prefix)&&(category==='all'||e.type===category));
 const offset=(new Date(Date.UTC(y,m,1)).getUTCDay()+6)%7,weekStart=Math.floor((offset+day-1)/7)*7;
 const cells=Array.from({length:Math.ceil((offset+count)/7)*7},(_,i)=>i-offset+1).filter((_,i)=>view==='month'||(i>=weekStart&&i<weekStart+7));
 function move(n){setMonth(new Date(Date.UTC(y,m+n,1)));setDay(1)}
 return <main className="cal-main"><div className="cal-heading"><div><span className="cal-eyebrow">OFFICIAL DATA OBSERVATORY</span><h1>시장 캘린더</h1><p>공식 발표 일정과 검증된 사건 기록</p></div><div className="cal-month"><Button isIconOnly variant="ghost" aria-label="이전 달" title="이전 달" onPress={()=>move(-1)}><ChevronLeft size={18}/></Button><strong>{y}년 {m+1}월</strong><Button isIconOnly variant="ghost" aria-label="다음 달" title="다음 달" onPress={()=>move(1)}><ChevronRight size={18}/></Button><Button size="sm" variant="outline" onPress={()=>{setMonth(new Date(Date.UTC(today.getFullYear(),today.getMonth(),1)));setDay(today.getDate())}}>오늘</Button></div></div>
 <MonthlyDrivers year={y} month={m} count={count} day={day} onDay={setDay}/>
 <section><div className="cal-section-heading"><h2><CalendarDays size={18}/> 증시 캘린더</h2><div className="cal-segments">{[['month','월별'],['week','주별']].map(([id,label])=><Button key={id} size="sm" variant={view===id?'secondary':'ghost'} onPress={()=>setView(id)}>{label}</Button>)}</div></div><div className="cal-filters"><div className="cal-segments">{[['all','전체'],...Object.entries(labels)].map(([id,label])=><Button key={id} size="sm" variant={category===id?'secondary':'ghost'} onPress={()=>setCategory(id)}>{label}</Button>)}</div><span>수집 일정·발표 {events.length}건</span></div>{error&&<p className="cal-warning">자동 수집 기록 로드 실패 · {error}</p>}<div className="schedule-legend">{Object.entries(labels).map(([id,label])=><span key={id}><i className={id}/>{label}</span>)}</div><div className="month-grid-scroll"><div className="month-grid">{['월','화','수','목','금','토','일'].map(d=><div className="weekday" key={d}>{d}</div>)}{cells.map((n,i)=>{const valid=n>0&&n<=count,items=events.filter(e=>e.day===n);return <div key={i} className={`calendar-cell ${!valid?'outside':''} ${valid&&day===n?'chosen':''}`}><button className="calendar-date" disabled={!valid} aria-label={valid?`${m+1}월 ${n}일 일정`:'이 달 외 날짜'} onClick={()=>setDay(n)}>{valid?n:''}</button>{items.slice(0,3).map(e=><button key={e.id} className={`calendar-event ${e.type}`} title={`${e.title} · ${e.time}`} onClick={()=>setDay(n)}><span>{e.title}</span><small>{e.time}</small></button>)}{items.length>3&&<button onClick={()=>setDay(n)} className="more-events">+ {items.length-3}개 더보기</button>}</div>})}</div></div><div className="date-detail" aria-live="polite"><div className="date-detail-heading"><strong>{date}</strong><span>{events.filter(e=>e.day===day).length}개 수집 기록 · {verifiedSessions[date]?'장후 검증 리포트 있음':'분석 리포트 미확보'}</span>{verifiedSessions[date]&&<a href={`/report?date=${date}`}>리포트 <ArrowUpRight size={13}/></a>}</div>{events.filter(e=>e.day===day).map(e=><article className="schedule-detail" key={e.id}><span className={`event-type ${e.type}`}>{labels[e.type]}</span><div><h3>{e.title}</h3><p>{e.note}</p><small>{e.time}{e.drivers.length>0&&` · 관찰 후보: ${e.drivers.join(' / ')}`}</small></div><a href={e.url} target="_blank" rel="noreferrer">{e.source} <ExternalLink size={12}/></a></article>)}{!events.some(e=>e.day===day)&&<p className="fine">수집된 일정이 없습니다. 발표 부재나 영향 부재를 뜻하지 않습니다.</p>}</div><p className="fine">예정 일정: BLS·연준·Tesla IR 수동 검토 2026.10.04 · 발표 목록: 공식 RSS 자동 수집. 예정 일정의 Driver는 관찰 후보이며 실제 반응과 구분합니다.</p></section><OfficialFeed date={date}/></main>
}
