import React,{useState} from 'react';
import {Button,Modal} from '@heroui/react';
import {ChevronLeft,ChevronRight,ArrowUpRight,CalendarDays,ChartNoAxesCombined,ExternalLink} from 'lucide-react';
import {drivers,sources} from './report.js';
import {calendarEvents,driverSnapshots,monthDays} from './calendar-data.js';
import './styles.css';import './dark.css';import './calendar.css';
import MonthlyDrivers from './monthly-drivers.jsx';
import './framework.css';
const labels={economic:'경제지표',institution:'기관 이벤트',earnings:'실적 발표'};
function Segments({items,value,onChange,label}){return <div className="cal-segments" aria-label={label}>{items.map(([id,text])=><Button key={id} size="sm" variant={value===id?'secondary':'ghost'} aria-pressed={value===id} onPress={()=>onChange(id)}>{text}</Button>)}</div>}
export default function CalendarPage(){const [month,setMonth]=useState(new Date(Date.UTC(2026,9,1))),[session,setSession]=useState('all'),[category,setCategory]=useState('all'),[region,setRegion]=useState('all'),[view,setView]=useState('month'),[day,setDay]=useState(2),[point,setPoint]=useState(null);
 const y=month.getUTCFullYear(),m=month.getUTCMonth(),count=monthDays(y,m),loaded=y===2026&&m===9;
 const events=loaded?calendarEvents.filter(e=>(category==='all'||e.type===category)&&(region==='all'||e.region===region)):[];
 const points=loaded&&session!=='pre'?driverSnapshots:[];
 const offset=(new Date(Date.UTC(y,m,1)).getUTCDay()+6)%7,weekStart=Math.floor((offset+day-1)/7)*7;
 const cells=Array.from({length:Math.ceil((offset+count)/7)*7},(_,i)=>i-offset+1).filter((_,i)=>view==='month'||(i>=weekStart&&i<weekStart+7));
 function move(n){setMonth(new Date(Date.UTC(y,m+n,1)));setDay(1);setPoint(null);}
 return <><header><div className="topbar"><a className="brand" href="/dashboard.html"><ChartNoAxesCombined size={23}/>Trading<span className="brand-accent">Metrix</span></a><nav className="cal-nav"><a href="/dashboard.html">시장 캘린더</a><a href="/report">일일 리포트</a></nav><span className="cal-zone">미국 시장 · ET 기준</span></div></header><main className="cal-main"><div className="cal-heading"><div><span className="cal-eyebrow">MONTHLY OBSERVATORY</span><h1>시장 캘린더</h1><p>다가오는 발표와 기록된 반응을 한 시간축에서</p></div><div className="cal-month"><Button isIconOnly variant="ghost" aria-label="이전 달" title="이전 달" onPress={()=>move(-1)}><ChevronLeft size={18}/></Button><strong>{y}년 {m+1}월</strong><Button isIconOnly variant="ghost" aria-label="다음 달" title="다음 달" onPress={()=>move(1)}><ChevronRight size={18}/></Button><Button size="sm" variant="outline" onPress={()=>{setMonth(new Date(Date.UTC(2026,9,1)));setDay(4);}}>기준일</Button></div></div>
 <MonthlyDrivers year={y} month={m} count={count} loaded={loaded} day={day} onDay={setDay}/>
 <section><div className="cal-section-heading"><div><h2><CalendarDays size={18}/> 증시 캘린더</h2><p>경제지표 · 기관 일정 · 기업 실적</p></div><Segments items={[[ 'month','월별'],['week','주별']]} value={view} onChange={setView}/></div><div className="cal-filters"><Segments label="일정 유형" items={[[ 'all','전체'],...Object.entries(labels)]} value={category} onChange={setCategory}/><Segments label="지역" items={[[ 'all','전체 지역'],['US','미국'],['KR','한국']]} value={region} onChange={setRegion}/><span>확인 일정 {events.length}건</span></div><div className="schedule-legend">{Object.entries(labels).map(([id,text])=><span key={id}><i className={id}/>{text}</span>)}</div>{(!loaded||region==='KR')&&<p className="cal-warning">{region==='KR'?'한국 일정':'이 달 일정·반응'}은 아직 수집하지 않았습니다. 빈 날짜는 발표가 없다는 의미가 아닙니다.</p>}<div className="month-grid-scroll"><div className="month-grid">{['월','화','수','목','금','토','일'].map(d=><div className="weekday" key={d}>{d}</div>)}{cells.map((n,i)=>{const valid=n>0&&n<=count,items=events.filter(e=>e.day===n);return <div key={i} className={`calendar-cell ${!valid?'outside':''} ${valid&&day===n?'chosen':''}`}><button className="calendar-date" disabled={!valid} aria-label={valid?`${m+1}월 ${n}일 일정`:'이 달 외 날짜'} onClick={()=>setDay(n)}>{valid?n:''}{loaded&&n===4&&<small>기준일</small>}</button>{items.slice(0,3).map(e=><button key={e.id} className={`calendar-event ${e.type}`} title={`${e.title} · ${e.time}`} onClick={()=>setDay(n)}><span>{e.title}</span><small>{e.time}</small></button>)}{items.length>3&&<button onClick={()=>setDay(n)} className="more-events">+ {items.length-3}개 더보기</button>}</div>})}</div></div><div className="date-detail" aria-live="polite"><div className="date-detail-heading"><strong>{m+1}월 {day}일</strong><span>{events.filter(e=>e.day===day).length}개 일정 · {loaded&&day===2?'장후 반응 기록 있음':'반응 기록 미확보'}</span>{loaded&&day===2&&<a href="/report">리포트 연결 <ArrowUpRight size={13}/></a>}</div>{events.filter(e=>e.day===day).map(e=><article className="schedule-detail" key={e.id}><span className={`event-type ${e.type}`}>{labels[e.type]}</span><div><h3>{e.title}</h3><p>{e.note}</p><small>{e.time} · 미국 · 관찰 요인: {e.drivers.join(' / ')}</small></div><a href={e.url} target="_blank" rel="noreferrer">{e.source} <ExternalLink size={12}/></a></article>)}{!events.some(e=>e.day===day)&&<p className="fine">현재 필터에서 수집된 일정이 없습니다. 전체 일정의 부재를 확인한 것은 아닙니다.</p>}</div><p className="fine">BLS·연준·Tesla IR 공식 일정 선별 수집 · 검토 2026.10.04 · 자동 갱신 미연결 · 일정 변경 가능. 예정 일정의 Driver는 관찰 후보이지 실제 반응이 아닙니다.</p></section><footer><span>1D1P · Monthly Market Calendar</span><a href="/report">일일 리포트와 근거 추적 ↗</a></footer></main>
 <Modal><Modal.Backdrop isOpen={!!point} onOpenChange={open=>{if(!open)setPoint(null)}}><Modal.Container><Modal.Dialog className="stock-modal"><Modal.CloseTrigger/><Modal.Header><Modal.Heading>{point?.name} · 장후 반응</Modal.Heading></Modal.Header><Modal.Body>{point&&<div className="point-detail"><p>{point.date} · 강도 {point.score}/5</p><h3>{point.observation}</h3><p className="point-path">{point.path}</p><p>{point.detail}</p><p className="fine">시험 산식: {point.rule} · 올림 후 최대 5단계. 사후 재구성된 기록입니다.</p><a target="_blank" rel="noreferrer" href={sources.find(s=>s.id===point.source).url}>확인 출처 <ExternalLink size={12}/></a><a href="/report#evidence-trace">종목 연결 근거 <ArrowUpRight size={13}/></a></div>}</Modal.Body></Modal.Dialog></Modal.Container></Modal.Backdrop></Modal></>;
}
