import React,{createContext,useContext,useState} from 'react';
import {Button} from '@heroui/react';
import {ShieldCheck,LogOut,ExternalLink} from 'lucide-react';
const Context=createContext(null);
export function useCredentialStore(){return useContext(Context)}
export function SecretSave({provider,credentials,onResult,onClear}){const store=useCredentialStore();const [pending,setPending]=useState(false);const ready=Object.values(credentials).every(value=>typeof value==='string'&&value.trim());async function save(){if(pending||!store?.authenticated)return;setPending(true);try{const result=await store.persist(provider,Object.fromEntries(Object.entries(credentials).map(([name,value])=>[name,value.trim()])));onResult({ok:true,text:result.message})}catch(e){onResult({ok:false,text:e.message||'암호화 저장 실패'})}finally{onClear();setPending(false)}}const state=store?.saved?.[provider];return <div className="credential-save"><Button type="button" variant="secondary" isDisabled={!store?.authenticated||!ready||pending} onPress={save}><ShieldCheck size={15}/>{pending?'저장 중':provider==='alpaca'?'Alpaca 암호화 저장':'OpenAI 암호화 저장'}</Button><small>{state?.configured?`암호화 저장됨${state.updatedAt?` · ${new Date(state.updatedAt).toLocaleString('ko-KR')}`:''}`:store?.authenticated?'저장된 키 없음':'관리자 인증 후 저장 가능'}</small></div>}
export default function CredentialStore({children}){const [draft,setDraft]=useState(''),[token,setToken]=useState(''),[saved,setSaved]=useState(null),[pending,setPending]=useState(false),[message,setMessage]=useState(null);async function call(auth,body){const r=await fetch('/api/credentials',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${auth}`},body:JSON.stringify(body),cache:'no-store'});const data=await r.json();if(!r.ok)throw Error(data.message||'저장소 요청 실패');return data}
 async function authenticate(e){e.preventDefault();setPending(true);setMessage(null);try{const data=await call(draft.trim(),{action:'status'});if(data.owner!=='simhocheol')throw Error('관리자 인증 실패');setToken(draft.trim());setSaved(data.saved);setMessage('simhocheol 관리자 인증 완료. 저장 상태만 조회하며 키 원문은 불러오지 않습니다.')}catch(e){setToken('');setSaved(null);setMessage(e.message||'관리자 인증 실패')}finally{setDraft('');setPending(false)}}
 async function persist(provider,credentials){if(!token)throw Error('먼저 관리자 인증을 완료해 주세요.');const data=await call(token,{action:'save',provider,...credentials});if(data.persisted!==true)throw Error('저장 완료를 확인하지 못했습니다.');setSaved(prev=>({...prev,[provider]:{configured:true,updatedAt:data.updatedAt}}));return data}
 function logout(){setToken('');setDraft('');setSaved(null);setMessage(null)}
 return <Context.Provider value={{authenticated:!!token,saved,persist}}><section className="api-settings"><div className="api-section-heading"><ShieldCheck size={19}/><h2>암호화 키 저장</h2><span>{token?'simhocheol 인증됨':'관리자 인증 필요'}</span></div><p className="fine">키는 GitHub Actions Secrets에 공개키 암호화로 보관됩니다. 브라우저를 닫거나 서버를 재배포해도 유지됩니다. 관리자 토큰은 현재 화면 메모리에서만 사용합니다.</p>{token?<Button variant="outline" onPress={logout}><LogOut size={15}/> 관리자 인증 해제</Button>:<form onSubmit={authenticate}><label htmlFor="credential-admin-token">GitHub 관리자 토큰</label><div className="api-key-row"><input id="credential-admin-token" type="password" autoComplete="off" spellCheck={false} autoCapitalize="none" maxLength={300} value={draft} onChange={e=>setDraft(e.target.value)} placeholder="github_pat_..." disabled={pending} required/><Button type="submit" variant="primary" isDisabled={pending||!draft.trim()}><ShieldCheck size={15}/>{pending?'확인 중':'관리자 인증'}</Button></div></form>}{message&&<p role="status">{message}</p>}<p className="fine">Fine-grained 토큰: 소유자 simhocheol · 저장소 1D1P만 선택 · Repository permissions의 Secrets를 Read and write로 지정하세요. 만료일을 설정하고 사용하지 않을 때 폐기하세요.</p><a href="https://github.com/settings/personal-access-tokens/new" target="_blank" rel="noreferrer">관리자 토큰 발급 <ExternalLink size={13}/></a></section>{children}</Context.Provider>}
