import React, {useState} from 'react';
import {Button, Chip} from '@heroui/react';
import {Landmark, ExternalLink} from 'lucide-react';

export const institutions=[
 {id:'fed',name:'연준',english:'Federal Reserve',status:'발표 확인',items:[
  {title:'Regulation O 의견수렴 기간 연장',time:'10.02 · 16:00 EDT · 정규장 마감 시각',summary:'은행 내부자 대출 규정 개정안에 대한 의견 제출 기한을 11월 4일까지 연장한다고 발표했습니다.',path:'은행 규제 절차 → 금융업 감독·준법',impact:'직접 시장 영향 미검증',note:'절차 변경이며 금리 결정 발표가 아닙니다. 당일 주가 반등의 원인으로 연결하지 않습니다.',url:'https://www.federalreserve.gov/newsevents/pressreleases/bcreg20261002a.htm'}]},
 {id:'treasury',name:'재무부',english:'U.S. Treasury',status:'발표 확인',items:[
  {title:'우크라이나 에너지·핵심광물 투자 승인',time:'10.02 · 게시 시각 미확인',summary:'미·우크라이나 재건 투자펀드가 핵심광물과 에너지 분야의 추가 투자·파트너십을 승인했다고 발표했습니다.',path:'재건 투자 → 공급망·에너지 안보 → 광물·전력·저장장치',impact:'분야 연관성 있음 · 가격 영향 미검증',note:'장기 투자 경로에 대한 분석 가설입니다. 당일 금속 가격이나 특정 미국 종목 반응을 확인한 것은 아닙니다.',url:'https://home.treasury.gov/news/press-releases/sb0648/'},
  {title:'Hamas 자금조달 네트워크 제재',time:'10.02 · 게시 시각 미확인',summary:'OFAC는 Hamas 자금조달에 연관된 개인과 단체를 제재 대상으로 지정했다고 발표했습니다. 암호화폐를 통한 자금 이전도 언급했습니다.',path:'제재 지정 → 거래 제한·준법 → 금융·디지털자산 사업자',impact:'규제 연관성 있음 · 가격 영향 미검증',note:'암호화폐가 언급됐다는 이유로 BTC 가격 방향이나 유가 충격을 추정하지 않습니다.',url:'https://home.treasury.gov/news/press-releases/sb0647/'}]},
 {id:'whitehouse',name:'백악관',english:'White House',status:'발표 확인',items:[
  {title:'Medicare 보험료 지원금 발표',time:'10.02 · 게시 시각 미확인',summary:'백악관은 Medicare Part B 보험료 부담을 돕기 위해 2천만 명 이상의 가입자에게 1인당 90달러를 일회성 지급한다고 발표했습니다.',path:'지원금 → 가계 부담 경감 → 소비·헬스케어 관찰',impact:'정책 연관성 있음 · 가격 영향 미검증',note:'기업 매출·실적에 대한 영향은 별도 검토가 필요합니다. 당일 소비재 상승과의 인과관계는 확인하지 않았습니다.',url:'https://www.whitehouse.gov/fact-sheets/2026/10/fact-sheet-president-donald-j-trump-announces-medicare-improvement-fund-payments-for-seniors/'}]},
 {id:'state',name:'국무부 · 외교',english:'U.S. Department of State',status:'확인 실패',items:[],url:'https://www.state.gov/press-releases/',note:'공식 발표 페이지 접근 실패로 10월 2일 발표를 확인하지 못했습니다. 발표가 없었다는 의미가 아닙니다.'},
];

export default function InstitutionMap(){const [active,setActive]=useState('fed');const agency=institutions.find(x=>x.id===active);return <section className="institution-section" aria-label="기관 발표 맵"><div className="institution-heading"><Landmark size={19}/><div><h2>기관은 무엇을 발표했나</h2><p>2026.10.02 · 미국 기관 · 공식 원문 기반 선별 기록 · 10.04 검토</p></div></div><div className="institution-grid">{institutions.map(x=><Button variant="ghost" key={x.id} className={`institution-tile ${active===x.id?'selected':''}`} aria-pressed={active===x.id} aria-label={`${x.name} 발표 보기`} onPress={()=>setActive(x.id)}><span><strong>{x.name}</strong><b>{x.items.length?`${x.items.length}건 확인`:'—'}</b></span><small>{x.english}</small><Chip size="sm" variant="soft" className={`status ${x.items.length?'support':'neutral'}`}>{x.status}</Chip></Button>)}</div><div className="institution-detail" aria-live="polite"><div className="agency-title"><h3>{agency.name}</h3><span>선별 확인 건수이며 당일 전체 발표 건수가 아닙니다</span></div>{agency.items.length?agency.items.map(item=><article className="announcement" key={item.url}><div className="announcement-meta"><span>{item.time}</span><a href={item.url} target="_blank" rel="noreferrer">공식 원문 <ExternalLink size={12}/></a></div><h4>{item.title}</h4><p>{item.summary}</p><div className="announcement-path">{item.path}</div><div className="impact-line"><span>영향 판정</span><strong>{item.impact}</strong></div><p className="fine">{item.note}</p></article>):<div className="agency-empty"><strong>{agency.status}</strong><p>{agency.note}</p><a href={agency.url} target="_blank" rel="noreferrer">공식 발표 페이지 <ExternalLink size={12}/></a></div>}</div><p className="fine">원문 내용은 한국어 요약입니다. 가격 인과 효과는 정량 평가하지 않았습니다. ‘발표 없음’은 지정 기간의 공식 목록을 끝까지 확인한 경우에만 표시하며, 접근 실패·자료 부족과 구분합니다. 게시 시각이 없는 자료는 장 마감 전 발표 여부가 미확인입니다.</p></section>}
