import React,{useState} from 'react';
import {Button} from '@heroui/react';
import {CalendarDays,FileText,ListFilter,Settings,ArrowUpRight,Star,Check} from 'lucide-react';
import CalendarPage from './calendar.jsx';
import LegacyReportPage from './report-page.jsx';
import VerifiedReport,{AuditNavigation} from './verified-report.jsx';
import {report,pct,drivers} from './report.js';
import {evidenceLinks} from './trace-data.js';
import './service.css';
const routes=[['/','시장 캘린더',CalendarDays],['/report','일일 리포트',FileText],['/universe','종목·ETF',ListFilter],['/settings','발행 설정',Settings]];
function ReportPage(){const date=new URLSearchParams(location.search).get('date');return date?<VerifiedReport date={date}/>:<><div className="service-page"><AuditNavigation/></div><LegacyReportPage/></>}
function read(key,fallback){try{const value=JSON.parse(localStorage.getItem(key));return value??fallback}catch{return fallback}}
function Universe(){const [query,setQuery]=useState(''),[kind,setKind]=useState('all'),[watchOnly,setWatchOnly]=useState(false),[saved,setSaved]=useState(()=>{const v=read('1d1p-watch',[]);return Array.isArray(v)?v:[];});const stocks=report.stocks.filter(s=>kind!=='etf'&&(!watchOnly||saved.includes(s.symbol))&&`${s.symbol} ${s.name}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>Math.abs(b.change)-Math.abs(a.change));function toggle(s){const next=saved.includes(s)?saved.filter(x=>x!==s):[...saved,s];setSaved(next);try{localStorage.setItem('1d1p-watch',JSON.stringify(next))}catch{}}return <main className="service-page"><div className="service-heading"><span>UNIVERSE</span><h1>종목·ETF 변화 탐색</h1><p>가격 변화에서 Driver와 기업 노출까지</p></div><div className="scope-line">목표: S&P 500 구성 종목 + 선정 ETF <span>현재: 주식 5개 · ETF 미수집 · 10.02 마감 보도</span></div><div className="universe-tools"><input type="search" aria-label="종목 검색" placeholder="심볼 또는 기업명" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="자산 유형" value={kind} onChange={e=>setKind(e.target.value)}><option value="all">주식 + ETF</option><option value="stock">주식</option><option value="etf">ETF</option></select><Button size="sm" variant={watchOnly?'secondary':'outline'} aria-pressed={watchOnly} onPress={()=>setWatchOnly(!watchOnly)}><Star size={14}/> 관심 종목</Button><span>변화 크기순</span></div><div className="stock-table-wrap"><table><thead><tr><th>관심</th><th>종목</th><th>변화</th><th>연결된 Driver</th><th>검증 범위</th><th>근거</th></tr></thead><tbody>{stocks.map(s=><tr key={s.symbol}><td><Button isIconOnly size="sm" variant="ghost" title="관심 종목" aria-label={`${s.symbol} 관심 ${saved.includes(s.symbol)?'해제':'추가'}`} onPress={()=>toggle(s.symbol)}><Star size={16} fill={saved.includes(s.symbol)?'currentColor':'none'}/></Button></td><td><strong>{s.symbol}</strong><small>{s.name}</small></td><td className={s.change>0?'positive':'negative'}>{pct(s.change,s.approximate)}</td><td>{[...new Set(evidenceLinks.filter(e=>e.stocks.includes(s.symbol)).flatMap(e=>e.drivers))].join(' / ')}</td><td>보도 기반<small>노출 규모·인과 기여율 미추정</small></td><td><a href={`/report?stock=${s.symbol}#evidence-trace`}>추적 <ArrowUpRight size={13}/></a></td></tr>)}</tbody></table>{!stocks.length&&<div className="service-empty">{kind==='etf'?'ETF 데이터 수집은 아직 연결되지 않았습니다.':'조건에 맞는 기록이 없습니다.'}</div>}</div><p className="fine">약 10% 하락은 근사값입니다. 관심 종목은 현재 브라우저에 저장되며 계정 동기화는 미연결입니다.</p><div className="universe-coverage"><h2>추적 기준</h2><p>거시 6 + 산업·정책 3 + 기업 3</p><div>{drivers.map(d=><span key={d.id}>{d.name}</span>)}</div></div></main>}
const defaults={pre:'09:00',post:'16:30',timezone:'America/New_York',preEnabled:true,postEnabled:true};
function Preferences(){const [form,setForm]=useState(()=>({...defaults,...read('1d1p-preferences',{})})),[saved,setSaved]=useState(false);function change(key,value){setForm({...form,[key]:value});setSaved(false)}function submit(e){e.preventDefault();try{localStorage.setItem('1d1p-preferences',JSON.stringify(form));setSaved(true)}catch{setSaved(false)}}return <main className="service-page preferences"><div className="service-heading"><span>REPORT PREFERENCES</span><h1>발행 설정</h1><p>장전·장후, 하루 두 번의 관찰 기록</p></div><div className="scope-line">현재 상태: 로컬 설정 저장만 제공 <span>예약 실행·웹 푸시·모바일 알림은 미연결</span></div><form onSubmit={submit}><label className="preference-row"><span><strong>장전 리포트</strong><small>경제 일정과 관찰할 Driver</small></span><input type="checkbox" aria-label="장전 리포트 활성화" checked={form.preEnabled} onChange={e=>change('preEnabled',e.target.checked)}/><input required type="time" aria-label="장전 발행 시각" value={form.pre} onChange={e=>change('pre',e.target.value)}/></label><label className="preference-row"><span><strong>장후 리포트</strong><small>관측 사건·기업 노출·실제 반응</small></span><input type="checkbox" aria-label="장후 리포트 활성화" checked={form.postEnabled} onChange={e=>change('postEnabled',e.target.checked)}/><input required type="time" aria-label="장후 발행 시각" value={form.post} onChange={e=>change('post',e.target.value)}/></label><div className="preference-row"><span><strong>시간대</strong><small>서머타임은 실제 발행 엔진 연결 시 IANA 기준 적용</small></span><select aria-label="발행 시간대" value={form.timezone} onChange={e=>change('timezone',e.target.value)}><option value="America/New_York">미국 동부 · ET</option><option value="Asia/Seoul">한국 · KST</option></select></div><Button type="submit" variant="primary" size="sm">{saved?<Check size={15}/>:<Settings size={15}/>} {saved?'이 브라우저에 저장됨':'설정 저장'}</Button></form><p className="fine">설정 저장은 실제 예약·알림 등록이 아닙니다. 미국 휴장일 일정과 장전·장후 발행 시각 검증은 스케줄러 연결 단계에서 적용합니다.</p></main>}
export default function Service(){const path=location.pathname==='/dashboard.html'?'/':location.pathname;const route=routes.some(r=>r[0]===path)?path:'/';return <div className="service-shell"><header className="service-header"><a className="service-brand" href="/">1D1P<span>하루에 1퍼센트 먹기</span></a><nav aria-label="1D1P 메뉴">{routes.map(([href,label,Icon])=><a href={href} aria-current={route===href?'page':undefined} key={href}><Icon size={15}/><span>{label}</span></a>)}</nav><span className="service-mode">출처 기반 샘플</span></header><div className="service-content">{route==='/report'?<ReportPage/>:route==='/universe'?<Universe/>:route==='/settings'?<Preferences/>:<CalendarPage/>}</div><div className="service-disclaimer">1D1P는 시장 관찰·근거 추적 서비스입니다. 이름은 목표 표현이며 일일 1% 수익을 보장하지 않습니다.</div></div>}
