import React,{useState} from 'react';
import {Button} from '@heroui/react';
import {CalendarDays,FileText,ListFilter,Settings,Star} from 'lucide-react';
import CalendarPage from './calendar.jsx';
import VerifiedReport from './verified-report.jsx';
import OfficialFeed from './official-feed.jsx';
import {verifiedSessions,auditSources} from './verified-sessions.js';
import './service.css';
const routes=[['/','시장 캘린더',CalendarDays],['/report','일일 리포트',FileText],['/universe','종목·ETF',ListFilter],['/settings','수집 상태',Settings]];
const latest=Object.keys(verifiedSessions).sort().at(-1);
const stocks=[{symbol:'TSLA',name:'Tesla',date:'2026-10-02',change:4.7,driver:'매출·주문'},{symbol:'NKE',name:'NIKE',date:'2026-10-02',change:-3.6,driver:'매출·주문 / 마진·현금흐름'}];
function savedStocks(){try{const s=JSON.parse(localStorage.getItem('1d1p-watch')||'[]');return Array.isArray(s)?s:[]}catch{return []}}
function Universe(){const [query,setQuery]=useState(''),[kind,setKind]=useState('all'),[saved,setSaved]=useState(savedStocks);function toggle(symbol){const next=saved.includes(symbol)?saved.filter(s=>s!==symbol):[...saved,symbol];setSaved(next);try{localStorage.setItem('1d1p-watch',JSON.stringify(next))}catch{}}const selected=stocks.filter(s=>kind!=='etf'&&`${s.symbol} ${s.name}`.toLowerCase().includes(query.toLowerCase()));return <main className="service-page"><div className="service-heading"><span>VERIFIED OBSERVATIONS</span><h1>종목·ETF</h1><p>출처가 확인된 종목 반응</p></div><div className="scope-line">주식 2개 · 2026-10-02 마감 보도<span>가격 API · S&P 500 전체 · ETF 미연결</span></div><div className="universe-tools"><input type="search" aria-label="종목 검색" placeholder="심볼 또는 기업명" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="자산 유형" value={kind} onChange={e=>setKind(e.target.value)}><option value="all">주식 + ETF</option><option value="stock">주식</option><option value="etf">ETF</option></select></div><div className="stock-table-wrap"><table><thead><tr><th>관심</th><th>종목</th><th>날짜 · ET</th><th>보도 등락</th><th>Driver</th><th>근거</th></tr></thead><tbody>{selected.map(s=><tr key={s.symbol}><td><Button isIconOnly size="sm" variant="ghost" aria-label={`${s.symbol} 관심 ${saved.includes(s.symbol)?'해제':'추가'}`} title="관심 종목" onPress={()=>toggle(s.symbol)}><Star size={16} fill={saved.includes(s.symbol)?'currentColor':'none'}/></Button></td><td><strong>{s.symbol}</strong><small>{s.name}</small></td><td>{s.date}</td><td className={s.change>0?'positive':'negative'}>{s.change>0?'+':''}{s.change}%</td><td>{s.driver}</td><td><a href={`/report?date=${s.date}`}>발표·반응</a><small><a href={auditSources.close2.url} target="_blank" rel="noreferrer">마감 보도 ↗</a></small></td></tr>)}</tbody></table>{!selected.length&&<p className="service-empty">수집된 기록이 없습니다.</p>}</div><p className="fine">실시간 시세가 아닙니다. 보도 등락과 거래소 OHLCV를 구분합니다. 거래량·기술지표·매매 추천은 미제공입니다.</p></main>}
function CollectionStatus(){return <main className="service-page"><div className="service-heading"><span>DATA CONNECTIONS</span><h1>수집 상태</h1><p>공식 자료와 연결 상태</p></div><OfficialFeed statusOnly/><section><h2>자동 수집 · 배포</h2><p>GitHub Actions가 미국 동부 09시·17시의 예약 실행 구간에서 공식 RSS를 수집합니다. 서머타임은 America/New_York 기준으로 처리합니다. 실행 지연이 있을 수 있으며 휴장일에도 평일 수집합니다.</p><p>수집된 기록은 저장소에 보관됩니다. GitHub 변경은 연결된 Vercel 운영 배포로 반영됩니다. 일부 수집 실패 시 기존 기록을 유지하고 실패 상태를 공개합니다.</p><h2>미연결</h2><p>가격·OHLCV 제공처, 기관 원문 자동 분석, OpenAI 요약, 실적 일정 전수 수집, 웹·모바일 푸시는 아직 미연결입니다. API 키는 GitHub Secrets 또는 Vercel 서버 환경 변수에만 등록하며 브라우저로 보내지 않습니다.</p></section></main>}
export default function Service(){const path=location.pathname==='/dashboard.html'?'/':location.pathname;const route=routes.some(r=>r[0]===path)?path:'/';const date=new URLSearchParams(location.search).get('date')||latest;return <div className="service-shell"><header className="service-header"><a className="service-brand" href="/">1D1P<span>하루에 1퍼센트 먹기</span></a><nav aria-label="1D1P 메뉴">{routes.map(([href,label,Icon])=><a href={href} aria-current={route===href?'page':undefined} key={href}><Icon size={15}/><span>{label}</span></a>)}</nav><span className="service-mode">공식 자료 · 검증 기록</span></header><div className="service-content">{route==='/report'?<><VerifiedReport date={date}/><div className="service-page"><OfficialFeed date={date}/></div></>:route==='/universe'?<Universe/>:route==='/settings'?<CollectionStatus/>:<CalendarPage/>}</div><div className="service-disclaimer">1D1P는 시장 관찰·근거 추적 서비스입니다. 이름은 목표 표현이며 일일 1% 수익을 보장하지 않습니다.</div></div>}
