import React,{useState} from 'react';
import {Button,Chip} from '@heroui/react';
import {ArrowRight,ExternalLink,GitBranch} from 'lucide-react';
import {drivers,report,sources,pct,relative} from './report.js';
import {evidenceLinks} from './trace-data.js';
import {institutions} from './institutions.jsx';
export default function EvidenceTrace({onOpenStock}){
 const [symbol,setSymbol]=useState(()=>{const s=new URLSearchParams(window.location.search).get('stock');return report.stocks.some(x=>x.symbol===s)?s:'NKE';}),[driver,setDriver]=useState(null);
 const stock=report.stocks.find(s=>s.symbol===symbol);
 const shown=evidenceLinks.filter(e=>e.stocks.includes(symbol)&&(!driver||e.drivers.includes(driver)));
 const affected=driver?report.stocks.filter(s=>evidenceLinks.some(e=>e.drivers.includes(driver)&&e.stocks.includes(s.symbol))):report.stocks;
 function chooseDriver(name){setDriver(name);const candidate=evidenceLinks.find(e=>e.drivers.includes(name));if(candidate&&!candidate.stocks.includes(symbol))setSymbol(candidate.stocks[0]);}
 return <section className="trace-section" id="evidence-trace" aria-label="종목 변화 근거 추적"><div className="trace-title"><GitBranch size={19}/><div><h2>종목은 왜 움직였나</h2><p>관측된 변화 → 기업 근거 → 시장 배경 · 연결이 없으면 미확인</p></div></div><div className="trace-driver-filter"><Button variant={driver===null?'secondary':'ghost'} size="sm" aria-pressed={driver===null} onPress={()=>setDriver(null)}>전체 근거</Button>{drivers.map(d=><Button size="sm" variant={driver===d.name?'secondary':'ghost'} key={d.name} aria-pressed={driver===d.name} aria-label={`${d.name} 연결 추적`} onPress={()=>chooseDriver(d.name)}>{d.name}<span className="trace-count">{new Set(evidenceLinks.filter(e=>e.drivers.includes(d.name)).flatMap(e=>e.stocks)).size}</span></Button>)}</div><div className="trace-stock-selector">{affected.map(s=><Button variant={symbol===s.symbol?'secondary':'outline'} size="sm" key={s.symbol} aria-pressed={symbol===s.symbol} aria-label={`${s.symbol} 변화 추적`} onPress={()=>setSymbol(s.symbol)}>{s.symbol}<b className={s.change>0?'positive':'negative'}>{pct(s.change,s.approximate)}</b></Button>)}{affected.length===0&&<span>선택한 Driver에 기록된 종목 연결이 없습니다. 무관하다고 판단한 것은 아닙니다.</span>}</div><div className="trace-summary"><div><strong>{stock.symbol}</strong><span>{stock.name}</span><b className={stock.change>0?'positive':'negative'}>{pct(stock.change,stock.approximate)}</b></div><span>{stock.approximate?'약 ':''}시장 대비 {relative(stock.change)>0?'+':''}{relative(stock.change).toFixed(2)}%p · {driver?`${driver} 연결 검토`:'전체 근거 검토'}</span><Button size="sm" variant="ghost" onPress={()=>onOpenStock(stock)}>종목 상세 <ArrowRight size={14}/></Button></div>{shown.map(e=><article className="trace-evidence" key={e.id}><div className="trace-evidence-meta"><Chip size="sm" variant="soft" className={`status ${e.kind==='시장 공통 배경'?'mixed':'neutral'}`}>{e.kind}</Chip><span>{e.time}</span></div><h3>{e.title}</h3><p>{e.fact}</p><div className="trace-route">{e.drivers.map(name=><Button size="sm" variant="ghost" onPress={()=>chooseDriver(name)} key={name}>{name}</Button>)}<ArrowRight size={14}/><span>{e.path}</span><ArrowRight size={14}/><strong>{e.stocks.join(' · ')}</strong></div><p className="trace-limit">{e.limit}</p><a href={sources.find(s=>s.id===e.source).url} target="_blank" rel="noreferrer">{sources.find(s=>s.id===e.source).name} <ExternalLink size={12}/></a></article>)}{shown.length===0&&<div className="trace-empty">{stock.symbol}와 {driver} 사이의 확인된 설명 근거가 없습니다. 빈 연결을 추정으로 채우지 않았습니다.</div>}<div className="trace-agencies"><h3>기관 발표와의 직접 연결</h3>{institutions.map(a=><div key={a.id}><strong>{a.name}</strong><span>{a.items.length?'발표 확인 · 이 종목과의 직접 연결 미확인':'발표 확인 실패 · 종목 연결도 미확인'}</span></div>)}</div><p className="fine">연결망은 마감 보도에 기반한 설명 후보이며 자동 원인 분석·인과 검증 결과가 아닙니다. 숫자는 연결된 종목 수이지 영향력 점수가 아닙니다. 연결되지 않은 기관 발표도 위 기관 맵에 유지됩니다.</p></section>
}
