import React,{useEffect,useState} from 'react';
import {Button} from '@heroui/react';
import {Star,ShieldCheck} from 'lucide-react';
import SectorHeatmap from './sector-heatmap.jsx';
import {readDeviceVault} from './device-vault.js';
const number=v=>Number.isFinite(v)?v.toLocaleString('ko-KR',{maximumFractionDigits:2}):'—';
export default function Universe(){
 const [data,setData]=useState(null),[error,setError]=useState(''),[query,setQuery]=useState(''),[kind,setKind]=useState('all'),[sector,setSector]=useState('all'),[metrics,setMetrics]=useState({}),[news,setNews]=useState({}),[events,setEvents]=useState([]),[token,setToken]=useState(''),[secret,setSecret]=useState(''),[pending,setPending]=useState(false),[sort,setSort]=useState('symbol'),[selected,setSelected]=useState(null),[saved,setSaved]=useState(()=>{try{return JSON.parse(localStorage.getItem('1d1p-watch')||'[]')}catch{return []}});
 useEffect(()=>{fetch('/data/official-feed.json').then(r=>r.json()).then(d=>setEvents(d.events||[])).catch(()=>{});const c=new AbortController();fetch('/data/universe.json',{signal:c.signal,cache:'no-cache'}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(setData).catch(e=>{if(e.name!=='AbortError')setError('종목 목록이 아직 수집되지 않았습니다.')});return()=>c.abort()},[]);
 async function load(e,useDevice=false){e?.preventDefault();setPending(true);setError('');try{let auth={token:token.trim(),secret:secret.trim()};if(useDevice){const v=await readDeviceVault();if(!v.credentials?.token)throw Error('이 기기에 저장된 조회 연결이 없습니다. 일일 리포트에서 먼저 연결해 주세요.');auth=v.credentials}const r=await fetch('/api/market-data',{method:'POST',headers:{Authorization:`Bearer ${auth.token}`,'Content-Type':'application/json'},body:JSON.stringify({secretKey:auth.secret}),cache:'no-store'});const body=await r.json();if(!r.ok)throw Error(body.message);setMetrics(body.metrics||{});setNews(body.news||{})}catch(e){setError(e.message)}finally{setToken('');setSecret('');setPending(false)}}
 function toggle(symbol){const next=saved.includes(symbol)?saved.filter(s=>s!==symbol):[...saved,symbol];setSaved(next);localStorage.setItem('1d1p-watch',JSON.stringify(next))}
 const assets=(data?.assets||[]).filter(a=>(kind==='all'||a.kind===kind)&&(sector==='all'||a.sector===sector)&&`${a.symbol} ${a.name}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='symbol'?a.symbol.localeCompare(b.symbol):(metrics[b.symbol]?.[sort]??-Infinity)-(metrics[a.symbol]?.[sort]??-Infinity));
 return <main className="service-page"><div className="service-heading"><span>MARKET UNIVERSE</span><h1>종목·ETF</h1><p>S&P 500 구성 종목 · 주요 ETF</p></div><div className="scope-line">주식 {data?.assets.filter(a=>a.kind==='stock').length||0}개 · ETF {data?.assets.filter(a=>a.kind==='etf').length||0}개<span>일봉 수집 {data?.coverage||0}/{data?.total||0} · {data?.checkedAt?new Date(data.checkedAt).toLocaleString('ko-KR'):'수집 대기'}</span></div>
 <SectorHeatmap assets={data?.assets||[]} metrics={metrics}/><section className="api-settings"><h2>비공개 시세 조회</h2><Button type="button" variant="primary" onPress={()=>load(null,true)} isDisabled={pending}><ShieldCheck size={16}/>{pending?'조회 중':'이 기기 연결로 시세 조회'}</Button><form onSubmit={load}><label htmlFor="market-token">GitHub 관리자 토큰 · Actions: Read 권한</label><div className="api-key-row"><input id="market-token" type="password" value={token} onChange={e=>setToken(e.target.value)} autoComplete="off" disabled={pending} required/><input aria-label="시세 복호화용 Alpaca Secret Key" placeholder="Alpaca Secret Key · 복호화용" type="password" value={secret} onChange={e=>setSecret(e.target.value)} autoComplete="off" disabled={pending} required/><Button type="submit" isDisabled={pending||!token.trim()||!secret.trim()}><ShieldCheck size={16}/>{pending?'조회 중':'시세 조회'}</Button></div></form></section>{error&&<p role="alert">{error}</p>}
 <div className="universe-tools"><input aria-label="종목 검색" placeholder="심볼 또는 기업명" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="자산 유형" value={kind} onChange={e=>setKind(e.target.value)}><option value="all">주식 + ETF</option><option value="stock">주식</option><option value="etf">ETF</option></select><select aria-label="섹터" value={sector} onChange={e=>setSector(e.target.value)}><option value="all">전체 섹터</option>{[...new Set(data?.assets.map(a=>a.sector)||[])].sort().map(s=><option key={s}>{s}</option>)}</select><select aria-label="정렬" value={sort} onChange={e=>setSort(e.target.value)}><option value="symbol">심볼순</option><option value="change">등락률순</option><option value="volumeRatio">거래량 강도순</option><option value="rsi14">RSI순</option></select></div>
 <div className="stock-table-wrap"><table><thead><tr><th>관심</th><th>종목</th><th>섹터</th><th>거래일 ET</th><th>종가</th><th>등락 %</th><th>IEX 거래량</th><th>RSI 14</th><th>변화 근거</th></tr></thead><tbody>{assets.map(a=>{const m=metrics[a.symbol];return <tr key={a.symbol}><td><Button isIconOnly variant="ghost" aria-label={`${a.symbol} 관심 ${saved.includes(a.symbol)?'해제':'추가'}`} onPress={()=>toggle(a.symbol)}><Star size={16} fill={saved.includes(a.symbol)?'currentColor':'none'}/></Button></td><td><button className="symbol-detail" onClick={()=>setSelected(a)}>{a.symbol}</button><small>{a.name}</small></td><td>{a.sector}</td><td>{m?.date||'—'}</td><td>{number(m?.close)}</td><td className={m?.change>0?'positive':'negative'}>{number(m?.change)}</td><td>{number(m?.volume)}</td><td>{number(m?.rsi14)}</td><td>{news[a.symbol]?.length?`${news[a.symbol].length}건 관련 보도 · 인과 미확정`:'원인 미확인'}</td></tr>})}</tbody></table>{!assets.length&&<p>해당 종목이 없습니다.</p>}</div>
 {selected&&<section className="api-settings"><div className="api-section-heading"><h2>{selected.symbol} · {selected.name}</h2><Button variant="ghost" onPress={()=>setSelected(null)}>닫기</Button></div><p>{selected.sector} · {selected.industry}</p><p>20일 이평 {number(metrics[selected.symbol]?.sma20)} · 50일 이평 {number(metrics[selected.symbol]?.sma50)} · 거래량/이전 20일 평균 {number(metrics[selected.symbol]?.volumeRatio)}배</p><p>SPY 대비 등락 차이 {number(metrics[selected.symbol]?.relativeToSPY)}%p · 가격 상관은 원인 기여도가 아닙니다.</p><h3>Driver 관측 대리지표 · 최근 최대 60개 수익률</h3>{metrics[selected.symbol]?.associations?.map(p=><p key={p.symbol}>{p.label} ({p.symbol}) · 상관 {number(p.correlation)} · 베타 {number(p.beta)} · {p.samples}개 관측</p>)}<h3>관련 기업 보도 · 최근 7일</h3>{news[selected.symbol]?.length?news[selected.symbol].map((n,i)=><p key={i}><a href={n.url} target="_blank" rel="noreferrer">{n.title}</a><small> · {n.source} · {new Date(n.publishedAt).toLocaleString('ko-KR')}</small></p>):<p>확인한 관련 보도 없음 · 발표가 없었다는 뜻은 아닙니다.</p>}<h3>같은 거래일의 기관 발표 · 시장 공통 배경</h3>{events.filter(e=>metrics[selected.symbol]?.date===new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York'}).format(new Date(e.publishedAt))).map(e=><p key={e.url}><a href={e.url} target="_blank" rel="noreferrer">{e.title}</a></p>)}<p>관련 보도와 기관 발표는 검토할 근거이며, 종목 변화의 원인으로 확정하지 않습니다. 뉴스는 배치별 최근 최대 50건으로 전수 수집이 아닙니다.</p><a href={`https://www.tradingview.com/chart/?symbol=${encodeURIComponent(selected.symbol)}`} target="_blank" rel="noreferrer">TradingView</a></section>}
 <p className="fine">시세는 관리자 전용 · IEX 거래량은 전체 시장 거래량이 아닙니다. 분할 조정 일봉이며 배당 포함 수익률이 아닙니다. ETF는 주요 29종 선정 목록으로 전체 ETF가 아닙니다.</p>{data&&<a href={data.source} target="_blank" rel="noreferrer">구성 종목 출처 · 커뮤니티 관리 목록</a>}</main>;
}
